# Generated by Django 3.0.3 on 2020-03-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200301_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_str',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
